import os


BASE_DIR = os.path.abspath(os.path.dirname(__file__))

SECRET_KEY = 'king god oss'

DATABASE_HOST = '127.0.0.1'
DATABASE_USERNAME = 'oss'
DATABASE_PASSWORD = 'oss'
DEFAULT_DATABASE = 'imgtoss'

SQLALCHEMY_ECHO = True
SQLALCHEMY_BINDS = {
	DEFAULT_DATABASE: 'mysql+pymysql://{0}:{1}@{2}/{3}'.format(DATABASE_USERNAME, DATABASE_PASSWORD, DATABASE_HOST, DEFAULT_DATABASE)
}
SQLALCHEMY_TRACK_MODIFICATIONS = True
